server:
  port: 9010

spring:
  application:
    name: service-provider-alibaba-sentinel9010
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: service-provider-alibaba-sentinel9010-flow-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
