server:
  port: 8302

eureka:
  instance:
    hostname: service-eureka002
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://service-eureka001:8300/eureka/