mybatis:
  type-aliases-package: com.zhu.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://106.75.118.152:3306/seata_db_two?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-seata9291
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 9291