server:
  port: 8200


spring:
  application:
    name: service-consumer001

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka/,http://localhost:8302/eureka/