server:
  port: 9005

spring:
  application:
    name: service-consumer-nacos9005
  cloud:
    nacos:
      discovery:
        server-addr: 106.75.118.152:3333,106.75.118.152:4445,106.75.118.152:5555
  profiles:
    active: dev