mybatis:
  type-aliases-package: com.zhu.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://106.75.118.152:3306/seata_db_one?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-seata9290
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: SEATA_GROUP

server:
  port: 9290

seata:
  application-id: ${spring.application.name}
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: localhost:8091
  config:
    type: nacos
    nacos:
      namespace: ""
      serverAddr: localhost:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server #名称与服务端在nacos注册中心的名称一样
      serverAddr: localhost:8848
      group: SEATA_GROUP
      namespace: ""
      userName: "nacos"
      password: "nacos"
      cluster: default